### ISSUE TITLE
VM Console Error: ERROR Uncaught saga error (store.js):  TypeError: "t is undefined"

### ISSUE THREAD

**Issue by mikfra** [oVirt/ovirt-web-ui#1191] opened 2020-04-20 22:30 UTC
Description of problem [include screenshots and browser console logs]:
- When navigating to the https://ovirt.local/ovirt-engine/web-ui/?locale=en_US the VMconsole reports an error. "Sorry, VM Portal is currently having some issues.
Please refresh the page or log out and log back in. If the issue persists, please report a bug on GitHub."

However, other web URLs work such as ovirt.local/ovirt-engine/web-ui/vm/$VMID

VM Portal version number: Version 1.6.0-1
oVirt version number:  Software Version:4.3.9.4-1.el7
Browser and version:   Firefox: 68.7.0esr (32-bit)

Steps to Reproduce:
1. Connect to vmconsole 

[](url)
Expected results:
- Access to VMConsole list of VMs

Additional info:

Saga Error:
 error  Uncaught saga error (store.js):  TypeError: "t is undefined"
    toInternal transform.js:77
    toInternal transform.js:398
    r index.js:526
    C index.js:526
    r runtime.js:62
    u runtime.js:296
    t runtime.js:114

**Comment by sjd78** [comment] 2020-04-23 01:55
Duplicate of #1186

**Closed** 2020-04-23 02:16 UTC

**Comment by sgratch** [comment] 2020-04-23 09:22
> Duplicate of #1186

@sjd78 is it a dup of #1186 or of #1181?

**Comment by michalskrivanek** [comment] 2020-04-23 09:45
@sgratch why #1181? don't get distracted by the word "console", this report has nothing to do with console

**Comment by sgratch** [comment] 2020-04-27 11:02
> @sgratch why #1181? don't get distracted by the word "console", this report has nothing to do with console

Based on the uncaught saga error details then I guess you're right. Sorry for the confusion.
