### ISSUE TITLE
Loading balloon showing forever

### ISSUE THREAD

**Issue by nkovacne** [oVirt/ovirt-web-ui#1521] opened 2021-09-30 10:52 UTC
Description of problem [include screenshots and browser console logs]:

Once we log into the web-ui (as a standard user) we see the "Loading" balloon all the time, it doesn't dismiss.

VM Portal version number:

1.7.1

oVirt version number:

4.4.8.6

Browser and version:

Google Chrome 93.0.4577.63

Steps to Reproduce:
1. Open https://<ovirt-fqdn>
2. Log in as a standard non-administrative user.
3. The "Loading" balloon shows up in the top of the page.

Actual results:

It won't ever dismiss.

Expected results:

It should dismiss once everything has been loaded.

Additional info:

![Captura de pantalla de 2021-09-30 11-52-02](https://user-images.githubusercontent.com/10921680/135442315-ac82773c-0227-49bd-885d-1f4136663d0e.png)

**Comment by nkovacne** [comment] 2021-10-21 10:29
I'm attaching the requested logs.

[requested-logs.tar.gz](https://github.com/oVirt/ovirt-web-ui/files/7388186/requested-logs.tar.gz)

**Comment by sgratch** [comment] 2021-11-02 14:10
@nkovacne
After checking the attached logs, all looks ok except  one request which seems active (without a response) and that might cause the loading box to stay up:
`transport.js:78 http GET[39] 🡒 url: "/ovirt-engine/api/events?search=severity%3Derror", headers: {"Accept":"application/json","Authorization":"*****","Accept-Language":"es","Filter":true}`

This might happen if the events list is too large and/or there are networking delays.

Please check the following:
1. Is the logged in user an admin user or a non admin when this is happening on web-ui?
2. Can you please send the browser Network log from VM Portal while this is happening (F12 > Network)?
3. In addition, can you please check via the admin portal  if the events log is too large?  
Purging the events might help  (web admin->Notification Drawer-> Clear all), but please do that after sending the Network log mentioned in (2) so that we'll assure that this is the problem.

**Comment by nkovacne** [comment] 2021-11-02 14:34
Hi @sgratch,

1. It is a nonadmin user. With the 'admin' user this doesn't happen.
2. I'm attaching the requested logs.
3. Actually, the events log is empty at the time this happens.

I just realized the "loading" popup disappears after approximately 1:30 - 2:00 minutes after logging in. Not sure if this is actually a bug anymore, or if there's something that should be corrected to avoid such a long "loading" event.

With this user I have permissions over 3 VMs. The oVirt infrastructure as a whole has currently 1376 machines.

I hope this helps.

[ovirt.har.tar.gz](https://github.com/oVirt/ovirt-web-ui/files/7461456/ovirt.har.tar.gz)

**Comment by sgratch** [comment] 2021-11-15 17:31
@nkovacne 
1. Based on the attached browser network sniffing log, I can see that the query for all events takes  84532.0870000869 millisecond for the response which is ~ 1.24 min and that might cause the delay and "loading" popup to disappear only after approximately 1.24 mins in that case.

From your attached log:
```
Request:
 "method": "GET",
 "url": "https://fqdn/ovirt-engine/api/events?search=severity%3Derror",
......
 "response": {
          "status": 200,
          ....
        "startedDateTime": "2021-11-02T14:29:26.609Z",
        "time": 84532.0870000869,                    <-----------
        "timings": {
             "blocked": 1.624000117599964,
              "dns": -1,
               "ssl": -1,
              "connect": -1,
              "send": 0.068,
               "wait": **84527.12499974995**,        <-----------
               "receive": 3.2700002193450928,
               "_blocked_queueing": 1.4220001175999641
           }


2. I can also see that the events log is definitely not empty - the list of fetched events is large and 
that caused the long waiting time for the response. How can you see that the events log was empty?
3. Based on the log, the logged in user has  permissions for only 2 VMs and one Pool entity and not 3 VMs as you mentioned.

**Comment by nkovacne** [comment] 2021-11-16 08:43
Hi @sgratch,

2. Sorry, I opened the notification drawer but didn't realize the 'Alerts' subtab was open. Yes, the Events subtab has a lot of events. I just cleared them. Then I re-logged in as a non-admin user and now the 'loading' balloon disappears within a couple seconds.
3. Actually: 2 VMs and 1 VmPool. I should have mentioned that, sorry.

**Comment by sgratch** [comment] 2021-12-15 19:31
@nkovacne Sure, np.
So based on that this is not really a bug. Fetching a huge data of events might take time and this is a known issue. Logged in as a non admin user requires filtering those events based on user permissions and it takes even more time. 

We had a plan for refactoring of the events feature on web-ui but not sure when and if it will be done.

Anyway, you are most welcomed to contribute and help fixing/improving that if you want to.
Meanwhile, I suggest closing this issue.

**Comment by sgratch** [comment] 2022-01-24 13:21
Following previous comment, I'm closing this issue as Not a Bug.

**Closed by sgratch** 2022-01-24 13:21 UTC
