### ISSUE TITLE
Clicking on the OS label in the main VM grid doesn't show the VM detail card

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#726] opened 2018-08-17 12:30 UTC
Clicking on the OS label in the main VM grid won’t show the VM detail card. Tested in: ovirt-web-ui-1.4.2.0.20180814git2ec0a1e-1.fc28.noarch.rpm, Mozilla Firefox for Fedora version 61.0.1 (64-bit)

![screenshot from 2018-08-17 14-26-40](https://user-images.githubusercontent.com/39263962/44266231-0cb03200-a22a-11e8-930f-a913c57a1ffd.png)

**Comment by sgratch** [comment] 2019-12-08 23:11
@isaranova Is it still relevant? I can't reproduce it.

**Comment by isaranova** [comment] 2019-12-13 16:19
@sgratch Yes, clicking on the label still won't redirect me to the VM detail card. Might be by design though. Tested in: ovirt-web-ui-1.6.1-0.20191128.git6370196.el7.noarch, firefox-70.0.1-4.fc30.x86_64

**Comment by sgratch** [comment] 2020-01-08 14:34
@lwrigh please advise if this is still relevant based on the PF4 design. I'm not sure if it's a requirement anymore to click on VM's OS label.

**Comment by lwrigh** [comment] 2020-01-08 15:04
The purpose of the label is just to provide the user with surface level information so it is okay if the label does not bring the user to the VM details page.

**Comment by sgratch** [comment] 2020-01-08 15:14
@lwrigh @isaranova ok, so Im closing this issue since we won't fix it.
@isaranova please re-open if you think it's still required.

**Closed by sgratch** 2020-01-08 15:14 UTC
Labels: Severity: Low, Type: Bug
