### ISSUE TITLE
API Request for remote resources

### ISSUE THREAD

**Issue by artinu777** [oVirt/ovirt-web-ui#994] opened 2019-04-02 08:57 UTC
I wont send API request to remote recourses(API server).

VM Portal version number: 
const Product = {
  name: 'oVirt Basic Portal',
  version: '1.5.2',
  release: '0.20190401git3fc05c6',

  ovirtApiVersionRequired: {
    major: 4,
    minor: 0,
  },
}

oVirt version number:
Software Version:4.3.0.4-1.el7

Steps to Reproduce:
1. 
ADD:
/var/lib/docker/volumes/testvolume/_data/ovirtapi/transport.js

function httpPost2 ({ input, os2 }: { input: string, os2: string }) {
  // const requestId = notifyStart('POST', url)
  var xhttp = new XMLHttpRequest()
  xhttp.open('POST', `http://myserver:81/api/v1/create?vmid=${input}&os=${os2}`, true)
  xhttp.setRequestHeader('Content-type', 'application/x-www-form-urlencoded')
  xhttp.send('{}')
}
ADD:
/var/lib/docker/volumes/testvolume/_data/ovirtapi/index.js

  startTest2 ({ vmId, osId }: { vmId: string, osId: string }) {
    httpPost2({
      input: `${vmId}`,
      os2: `${osId}` })
  },
ADD:
/var/lib/docker/volumes/testvolume/_data/components/VmActions/index.js

.....
  const suspendConfirmation2 = (
      <ConfirmationModal
        title={msg.installOS()}
        body={
          <div id={`${idPrefix}-OS`}>
            <div>{msg.installOSQuestion()}</div>
            <div>{this.state.messgage}</div>
            <select name='cars' >
              <option value='226' onClick={() => this.setState((s) => { return { selectetOS: '226' } })}>CentOS 7</option>
            </select>
            <div>After Yes please Waiting for VM Start</div>
          </div>
        }
        confirm={{ title: msg.yes(), onClick: () => onstartTest({ selectetOSq: this.state.selectetOS }) }} />)

....

      {
        priority: 0,
        actionDisabled: (!isPool && !canStart(status)) || vm.getIn(['actionInProgress', 'start']),
        shortTitle: msg.installOS(),
        tooltip: msg.installOSQuestion(),
        className: 'btn btn-danger',
        id: `${idPrefix}-button-startTest`,
        confirmation: suspendConfirmation2,
      },
.....

export default withRouter(
  connect(
    (state, { vm }) => ({
      isEditable: vm.get('canUserEditVm') && state.clusters.find(cluster => cluster.get('canUserUseCluster')) !== undefined,
    }),
    (dispatch, { vm, pool }) => ({
      onShutdown: () => dispatch(shutdownVm({ vmId: vm.get('id'), force: false })),
      onRestart: () => dispatch(restartVm({ vmId: vm.get('id'), force: false })),
      onForceShutdown: () => dispatch(shutdownVm({ vmId: vm.get('id'), force: true })),
      onSuspend: () => dispatch(suspendVm({ vmId: vm.get('id') })),
      onstartTest: ({ selectetOSq }) => dispatch(startTest2({ vmId: vm.get('id'), osId: selectetOSq })),
      onRemove: ({ preserveDisks }) => dispatch(removeVm({ vmId: vm.get('id'), preserveDisks })),
      onStartPool: () => dispatch(startPool({ poolId: pool.get('id') })),
      onStartVm: () => dispatch(startVm({ vmId: vm.get('id') })),
      // onStartVm: () => dispatch(startTest1({ vmId: vm.get('id') })),
    })
  )(VmActions)
)

ADD:
/var/lib/docker/volumes/testvolume/_data/sagas.js
function* startTest2 (action) {
  yield startProgress({ vmId: action.payload.vmId, name: 'startTest2' })
  const result = yield callExternalAction('startTest2', Api.startTest2, action)
  yield stopProgress({ vmId: action.payload.vmId, name: 'startTest2', result })
}

Actual results:
I not JS coder, but  APP(ovirt-web-ui) in docker container send post request to may server 
After build into rpm and installing on server, APP don't sent post request 

Expected results:
APP sent post requests

**Comment by gregsheremeta** [comment] 2019-04-02 18:56
What exactly are you trying to accomplish?

In the docker container, the web server is webpack and it uses http-proxy-middleware. As an RPM, the webserver is Apache + Wildfly. That may be the root cause of the difference, but unfortunately I don't understand your goal.

**Comment by artinu777** [comment] 2019-04-03 09:57
I wont to add new button on ovirt-web-ui, button send API request to my server.
Is to way do this:
1. edit JS APP(ovir-web-ui)add new methods  and send request to my server(this is short trip)
2. edit JS APP add new methods, edit ovirt-engine add new methods and send request from ovirt-engine to my server(this is long trip)  


```
-------------------                                          ---------------   
| New Button      |  ----send API request to server--------> | My server   |
| on ovirt-web-ui |                                          ---------------     
-------------------



1
----------------                    ----------------
| ovirt-web-ui |   ---------API---> | ovirt-engine |
| JS APP       |                    | java         | 
----------------                    ----------------
        |                           ---------------- 
        |_________API new_________> |  Server APP  | 
                                    ----------------

2
----------------                    ----------------
| ovirt-web-ui |   ---------API---> | ovirt-engine |
| JS APP       |                    | java         | 
----------------                    |              |
        |_________API new_________> |              |
                                    |              |
                                    ----------------
                                            |
                                            |
                                         new API
                                            |
                                    ---------------- 
                                    |  Server App  | 
                                    ----------------     
```
Сan you tell me how to implement this or maybe there is already such a functional in ovirt-engine.

**Comment by gregsheremeta** [comment] 2019-04-04 01:16
if you want to go with path 1, look into CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS  I suspect that is the issue.

if you want to go with path 2, that would be pretty easy. Simply write a servlet in ovirt-engine that proxies the request to your Server App.

What does your Server App do?

cc @bond95 @sjd78 @sgratch

**Comment by artinu777** [comment] 2019-04-05 12:55
I don't use (Cloud-Init/Sysprep, ovirt-image-repository, iso) to deploy VMs, 
I use foreman to deploy VMs, dedicated servers (OS: centos, windows, debian). 

Server APP is database and managment tools for infrastructure. 

```
_______________________
| button reinstall OS|
| os name(id)        |        
-----------------------             ----------------
| ovirt-web-ui |   ---------API---> | ovirt-engine |
| JS APP       |                    | java         | 
----------------                    |              |
        |_________API new_________> |              |<-----|
                                    |              |      |
                                    ----------------      |
                                            |             |
                                            |             |
                                         new API          API(control VMS ) 
                                            |             | 
                                    ----------------      |
                                    |  Server App  |  ----|
                                    ----------------.
        ------------------             |       |                    
        |  DATABASE      | ------------|       |
        |  IP            |                     | 
        | serverID       |                  API send configuration   
        | configuration  |                  to foreman  
        ------------------                     |  
                                               |
                                    ---------------
                                    |foreman      |
                                    ---------------
                                      |         |
                                    -----     ------------------
                                    |VM |     |dedicated server|
                                    -----     ------------------    
```
I start read sourse code:  https://github.com/oVirt/ovirt-engine.git beut

**Comment by sgratch** [comment] 2022-05-31 17:32
is this still relevant? It is opened for a long time and therefore I'm closing this issue.
Please re-open is it is still relevant.

**Closed by sgratch** 2022-05-31 17:32 UTC
