### ISSUE TITLE
Memory utilization sparkline shows 0% even when the VM is running for a while with some memory usage

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#932] opened 2019-01-25 10:59 UTC
I have VM running for some minutes with memory used > 500 M all the time, but the sparkline shows all the time only 0%.

![screenshot from 2019-01-25 11-52-14](https://user-images.githubusercontent.com/29575480/51741938-8fba9b80-2098-11e9-88b8-35ef7fef8f6b.png)

Tested on master with ovirt-engine-4.3.0-0.8.master.20190122102235.git7a1ef10.el7.noarch

**Comment by gregsheremeta** [comment] 2019-01-30 01:46
@sjd78 any thoughts?

**Comment by gregsheremeta** [comment] 2019-02-07 20:56
ping @sjd78 any ideas what would cause this?

**Comment by sjd78** [comment] 2019-02-07 21:28
@gregsheremeta - That data comes from the DWH.  If DWH isn't tracking things then we have nothing to show.  Also, since there are not timestamps on DWH values, it could have been tracking some time in the past but stopped currently.  Finally, I'm not sure if VDSM or guest agent (ovirt vs qemu version issue?) does the "live" tracking and what does the historic tracking.

**Comment by sgratch** [comment] 2022-05-31 17:29
This is not reproduced to me on 1.8.1-1 version (oVirt 4.5.0) and therefore closing this.

**Closed by sgratch** 2022-05-31 17:29 UTC
Labels: Type: Bug
