### ISSUE TITLE
Console shown in use even if it is not

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#877] opened 2018-11-21 14:29 UTC
User1 opens a console, if user2 wants to open it, "Console in use, continue?" popup is shown. However, if user1 closes the console, user2 still gets the same popup even though console is not in use.

**Comment by gregsheremeta** [comment] 2018-11-21 20:31
Sorry, it's not actually a duplicate, but it's also something I don't think we can do about. Eventually the ticket will timeout iiuc, but there's not currently a way to know that someone else has closed / disconnected virt-viewer.

Maybe when we're using the novnc pf-react component it will be somewhat possible, but I'm not sure it'll ever be 100% accurate.

@michalskrivanek @sjd78 @bond95 thoughts?

**Comment by bond95** [comment] 2018-12-12 12:14
@samuelmacko 
This is actually not a bug, because:

1) ovirt-engine has very strict security rules. If console session is open you must explicitly allow other user to connect, to console.

2) ovirt-engine without installed guest agent on VM, cannot monitoring status of console sessions right.

This leads us to, if user want to allow other user to connect to console after console is closed, need to:

1) Allow in Admin Portal every user to connect to console (not recommended because of security reason)
![image](https://user-images.githubusercontent.com/3332176/49868986-4cb9a700-fe0f-11e8-9423-13504edd09c2.png)

2) Install guest agent and set in Admin Portal to VM shutdown after disconnect or VM reboot after disconnect
![image](https://user-images.githubusercontent.com/3332176/49869071-90acac00-fe0f-11e8-89ee-e95fb8a8fee0.png)

3) Or reboot VM explicitly.

**Comment by gregsheremeta** [comment] 2018-12-20 15:32
@samuelmacko was strict user checking enabled when you originally reported?

**Comment by gregsheremeta** [comment] 2019-01-06 01:13
I think all is ok here, closing

**Closed by gregsheremeta** 2019-01-06 01:13 UTC
