### ISSUE TITLE
allow select quota at VM creation

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#770] opened 2018-09-13 11:14 UTC
Set quotas to auditing or enforcing mode.  Create a new quota and add a user as consumer.  

Steps to Reproduce:
1.  In Admin panel. Go to Settings > Quota
2.  Create a new quota and assign a user as a consumer
3.  Go to Compute > Data Centers
4.  Select the target Data Center
5.  Click edit
6.  Change Quota Mode to Audit or Enforced
7.  Login to VM portal as user
8.  Click 'Add new VM'
9.  Observer that there is no quota selection.

Actual results:

User should be able to select the assigned quota in the VM portal when creating a new personal VM.

Expected results:

User doesn't have a quota drop down selection.  VM will use whatever quota the template is assigned to.

**Comment by bond95** [comment] 2018-10-25 12:50
Duplicate of this bug https://github.com/oVirt/ovirt-web-ui/issues/744

**Closed by bond95** 2018-10-25 12:50 UTC
Labels: enhancement, severity_medium
