### ISSUE TITLE
mobile: click somewhere else in the VMs detail doesn't hide the help over the label on mobile device

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#368] opened 2017-10-31 08:46 UTC
Tested on iPad with Safari. Only click on the same label hides the help. The help stays visible when scrolling right in the VM detail.

**Comment by jniederm** [comment] 2017-11-01 19:39
* *popups being stuck while scrolling*: reproducible on desktop Firefox and Chrome as well
* *popups not closed by side-click*: It seems to be a problem of the react-bootstrap library on ios safari. It works on desktop & android Firefox. [Official demo][1] doesn't work on ios safari as well. Update to the latest version `0.31.5` doesn't help. We can re-implement functionality of "side-click to close". [POC][2] working on ios safari as well. It causes a flicker during each page click on ios safary though.

[1]: https://react-bootstrap.github.io/components.html#popovers-trigger-behaviors
[2]: http://jsbin.com/bamopogewi/edit?html,js,console,output

**Comment by jniederm** [comment] 2017-11-02 12:40
*popups being stuck while scrolling* blocked on https://github.com/react-bootstrap/react-bootstrap/issues/2869

**Comment by gregsheremeta** [comment] 2018-07-31 00:29
obsoleted by redesign. we'll make sure to test redesign on mobile devices.

**Closed by gregsheremeta** 2018-07-31 00:29 UTC
Labels: blocked, minor

**Comment by ReactGirl** [comment] 2018-10-04 08:28
This is still happening
https://github.com/react-bootstrap/react-overlays/issues/158
