### ISSUE TITLE
Can't continue creating a VM

### ISSUE THREAD

**Issue by sandrobonazzola** [oVirt/ovirt-web-ui#1207] opened 2020-05-11 15:01 UTC
Description of problem [include screenshots and browser console logs]:

VM Portal version number: ovirt-web-ui-1.6.1-1.el8.noarch

oVirt version number: 4.4.0 RC1

Browser and version: Google Chrome 81.0.4044.138

Steps to Reproduce:
1. deploy the system, node up but no storage attached
2. go to web admin
3. try to create a vm

Actual results:
the dialog opens and allow you to enter data but it doesn't enable the next button, only the cancel button. This make sense because the storage is missing but there's no indication in the dialog or on the portal that something is missing in order to create a VM.

![create_vm](https://user-images.githubusercontent.com/937860/81576742-e8569a80-93a8-11ea-84a8-b9a6d487aa46.png)

Expected results:
Something should say the reason for not enabling the next button

Additional info:

**Comment by bamsalem** [comment] 2020-06-03 04:32
Hi @sandrobonazzola ,
thank you for reporting, we tried to investigate the issue you reported and we unable reproduce it.
We followed the steps to reproduce the problem but the "Next" button still enabled.
Can you give us more details like which machine do you use , or any other details that might help us?
Thanks

**Comment by sandrobonazzola** [comment] 2020-06-03 15:28
I was just using oVirt Node attached to a CentOS 8.1 running ovirt-engine, nothing really special.

**Comment by michalskrivanek** [comment] 2020-06-04 08:26
> Hi @sandrobonazzola ,
> thank you for reporting, we tried to investigate the issue you reported and we unable reproduce it.
> We followed the steps to reproduce the problem but the "Next" button still enabled.
> Can you give us more details like which machine do you use , or any other details that might help us?
> Thanks

"This make sense because the storage is missing but there's no indication in the dialog or on the portal that something is missing in order to create a VM."

we can try to block the Create VM button as we do that for permissions anyway.

**Comment by sgratch** [comment] 2020-06-04 10:36
> "This make sense because the storage is missing but there's no indication in the dialog or on the portal that something is missing in order to create a VM."
> 
> we can try to block the Create VM button as we do that for permissions anyway.

@michalskrivanek I agree but I wonder how @sandrobonazzola reproduced the scenario of a disabled "next" button, because it isn't reproduced to me as long as all fields are set which is this case.

**Comment by sgratch** [comment] 2020-06-04 17:44
@sandrobonazzola @michalskrivanek @bamsalem In case a user doesn't have permissions to create a VM, the "create VM" button is hidden. But we can't do that in this case since we can't anticipate which DC the user would like to create the VM on. We can only do that in case all existed DC's are not attached to a SD.
Anyway, the scenario described by @sandrobonazzola is not reproduced so closing this issue.

Please re-open in case you succeed to reproduce this.

**Closed by sgratch** 2020-06-04 17:44 UTC
