### ISSUE TITLE
CreteVmWizard - misalign "Save" "Cancel" buttons when vertical scrollbar appears

### ISSUE THREAD

**Issue by bamsalem** [oVirt/ovirt-web-ui#1322] opened 2020-11-04 11:09 UTC
This issue is firstly mentioned [here](https://github.com/oVirt/ovirt-web-ui/pull/1301#pullrequestreview-501917545).

In The create Vm wizard when the vertical scroll bar appears the `TableInlineEditRow` aligned to the wrong position.

The issue caused by the stale values which provided to the `buttonsPosition` function.

You can find more details in #1301 and particularly in those comments:
1. [comment 1](https://github.com/oVirt/ovirt-web-ui/pull/1301#issuecomment-706710893).
2. [comment 2](https://github.com/oVirt/ovirt-web-ui/pull/1301#issuecomment-721107159)

Screenshots:
![size_wind](https://user-images.githubusercontent.com/13417815/95068115-1bf1e280-0705-11eb-903d-9e505053e08f.png)
![jumpingSaveCancel16th-2020-10-11_16 49 07](https://user-images.githubusercontent.com/64131213/95680451-8e216600-0be2-11eb-81bb-4131732c92a3.gif)

**Comment by hstastna** [comment] 2020-11-11 10:39
- 150% zooming and only 6 rows + no any change of the browser window size (1st scenario):
![output1](https://user-images.githubusercontent.com/13417815/97303447-b358da00-185a-11eb-8795-df20f8e3c4f1.gif)
 
When I include browser window size changes in the scenario or when zooming in more, the scenario is reproduced with much less items/rows. Reproduced in FF 78 ESR, FF 80, FF 82, Chromium.

**Comment by sgratch** [comment] 2021-02-24 16:07
Most problems related to this issue were solved in https://github.com/oVirt/ovirt-web-ui/pull/1301
The use case mentioned here is much more complicated to fix and less urgent since it is reproduced on a specific use case.
Therefore, we suggested to close this as WONTFIX until someone will complain and ask to re-open.

**Closed by sgratch** 2021-02-24 16:07 UTC
