### ISSUE TITLE
Warning appears occasionally: "Can't perform a React state update on an unmounted component..."

### ISSUE THREAD

**Issue by sgratch** [oVirt/ovirt-web-ui#1619] opened 2022-07-21 17:38 UTC
The following warning appears occasionally for me in few scenarios and not 100% reproduced. Try to run a VM with a snapshot and hot plugged another disk while the VM is starting up:
![image](https://user-images.githubusercontent.com/18169498/180273430-63700653-8a51-492b-804c-e9f811b97df0.png)

Another occurrence of this warning appears as follows:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in OverflowMenu (at VmDetailsActions.js:102)
    in VmDetailsActions (at VmActions/index.js:221)
    in VmActions (at MsgContext.js:12)
    in Unknown (created by Connect(Component))
    in Connect(Component) (created by Context.Consumer)
    in withRouter(Connect(Component)) (at Toolbar/index.js:34)
    in div (created by Context.Consumer)
    in ToolbarGroupWithRef (created by ForwardRef)
    in ForwardRef (at Toolbar/index.js:33)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in ToolbarContent (at Toolbar/index.js:32)
    in div (created by Context.Consumer)
    in GenerateId (created by Toolbar)
    in Toolbar (at Toolbar/index.js:31) react-dom.development.js:88
    React 6
        printWarning
        error
        warnAboutUpdateOnUnmountedFiberInDEV
        scheduleUpdateOnFiber
        enqueueSetState
        setState
    handleResize OverflowMenu.js:29
    timeout util.js:28
    (Async: setTimeout handler)
    debounce util.js:28
    (Async: EventListener.handleEvent)
    componentDidMount OverflowMenu.js:38
    React 6
        commitLifeCycles
        commitLayoutEffects
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        commitRootImpl
    unstable_runWithPriority scheduler.development.js:653
    React 5
        runWithPriority$1
        commitRoot
        finishSyncRender
        performSyncWorkOnRoot
        flushSyncCallbackQueueImpl
    unstable_runWithPriority scheduler.development.js:653
    React 4
        runWithPriority$1
        flushSyncCallbackQueueImpl
        flushSyncCallbackQueue
        batchedUpdates$1
    Redux 5
        notify
        notifyNestedSubs
        handleChangeWrapper
        dispatch
        sagaMiddleware
    routerMiddleware middleware.js:26
    Redux 4
        dispatch
        wrapSagaDispatch
        runPutEffect
        exec


```
VM Portal version number:
1.9.1-0

**Comment by rszwajko** [comment] 2022-08-18 15:17
Steps to re-create:
1. start VM Portal in small window (below `lg` breakpoint which is `992 px`)
2. enter VM Details and quickly resize to bigger window (above `lg` breakpoint)
3. check console logs

The root cause seems to be a bug in `OverflowMenu`  [componentWillUnmount()](https://github.com/patternfly/patternfly-react/blob/3c68c42f400f255e4ff47598dde0cb031455e811/packages/react-core/src/components/OverflowMenu/OverflowMenu.tsx#L49) implementation: `debounce()` produces an anonymous function so the existing handlers accumulate and trigger `handleResize()` on unmounted component.

**Comment by sgratch** [comment] 2022-09-07 13:11
@rszwajko can you please open a bug on this for patternfly-react?

**Comment by rszwajko** [comment] 2022-09-20 16:40
The PR with the fix has been merged - see https://github.com/patternfly/patternfly-react/pull/7975

**Comment by sgratch** [comment] 2022-09-28 22:46
For fixing on web-ui, need to upgrade patternfly/patternfly-react according to the following versions that includes the fix:
https://github.com/patternfly/patternfly-react/pull/7975#issuecomment-1252600927

**Closed** 2022-12-15 20:09 UTC
