### ISSUE TITLE
[RFE] Add ability to use NoVNC console in VM Portal

### ISSUE THREAD

**Issue by tonyjames** [oVirt/ovirt-web-ui#640] opened 2018-06-18 18:25 UTC
When using the VM Portal I do not see any option to select NoVNC as a console option when connecting to the console of a VM.  I use NoVNC extensively from the Admin Portal so it would be useful to have that same capability in the VM Portal.

**Comment by bond95** [comment] 2018-06-19 11:35
Yes, we have plan to do this feature, we already working on the component that can bring NoVNC functionality to VmPortal, https://github.com/patternfly/patternfly-react/pull/288

**Comment by mareklibra** [comment] 2018-06-19 12:21
Right, once https://github.com/patternfly/patternfly-react/pull/288 gets merged, it will be added here.

**Comment by gregsheremeta** [comment] 2018-08-01 01:27
duplicate of #490

**Closed by gregsheremeta** 2018-08-01 01:27 UTC
Labels: enhancement
