### ISSUE TITLE
adding a disk from web ui with a user who is a consumer of quota fails

### ISSUE THREAD

**Issue by gvasilopulos** [oVirt/ovirt-web-ui#682] opened 2018-07-28 21:42 UTC
if I try to create a new disk wit a user who is a consumer of quota I cannot with 
CREATE_DISK_FOR_VM failed
[Cannot add Virtual Disk. The user is not a consumer of the Quota assigned to the resource.]

I have created a diskless template to just to enable the specific quota in the template but that did not work either.
The quota has been set up accross all storage domains. 
What I'm trying to do is create a user, assign specific amount of resources and then let him create vm's up to those resources limit.

**Comment by gregsheremeta** [comment] 2018-08-29 14:36
duplicate of #744, closing

**Closed by gregsheremeta** 2018-08-29 14:36 UTC
Labels: bug
