### ISSUE TITLE
web-ui crashes on schedule update

### ISSUE THREAD

**Issue by bamsalem** [oVirt/ovirt-web-ui#1385] opened 2021-03-21 09:48 UTC
While I tested another change on vmDetails page of vm: `0f3880fc-fdb8-43c0-b352-a5eaba757412` on brq-dev
web ui crashes it seems like it's not related to the change I tested:
![image](https://user-images.githubusercontent.com/64131213/111900422-2f86d080-8a3b-11eb-914e-4ce1ee02a92e.png)

I couldn't reproduce that but it's worth checking.

**Comment by hstastna** [comment] 2021-03-22 14:36
I checked that VM in web-ui, also some other ones, played a little bit with snapshots, details, disks, NICs and wasn't able to reproduce the problem, on web-ui master branch or also web-ui on brq-dev. I suggest to close this issue. We can reopen it later anytime.

**Comment by sgratch** [comment] 2021-03-22 19:29
@bamsalem It seems that the  api/disks/c6a9cb2b-9e6c-4130-9f3c-6e9bedc4ae76/permissions?follow=role.permits returns 500 internal server error and that might cause the crash on permissionsToInternal since permissions.map was undefined. Not sure if worth fixing since it's an extreme case.

**Comment by bamsalem** [comment] 2021-03-24 11:01
OK,I know that is a server error but I raised it here so we can decide if it's worth fixing or create any checks before we calling permissions.map.
If you think that's an extreme case so let's close that issue :)
Better safe than sorry ;)

**Comment by sgratch** [comment] 2021-03-29 16:31
@bamsalem we can easily verify that permissions map is defined so let's do it. I'll assign this to you.

**Closed** 2021-04-08 16:35 UTC
