### ISSUE TITLE
clicking on a VM that is being installed (boot device is set to a CDROM) gives exception / page crash

### ISSUE THREAD

**Issue by gregsheremeta** [oVirt/ovirt-web-ui#692] opened 2018-08-01 21:09 UTC
clicking on a windows VM that is being installed (boot device is set to a CDROM) gives exception / page crash.

clicking on another windows VM that is powered off works fine.

```
compareVersion(), actual={"passed":true,"build":"0","full_version":"4.3.0_master","major":"4","minor":"3","revision":"0"}, required={"major":4,"minor":2}
helpers.js:20 External action getVm() starts on {"type":"GET_VM","payload":{"vmId":"e5b0c745-ae54-424d-bf61-598a1e3d26cf","shallowFetch":false,"additional":["cdroms","sessions","disk_attachments.disk","graphics_consoles","nics","snapshots"]}}
helpers.js:20 _httpGet start: url="/api/vms/e5b0c745-ae54-424d-bf61-598a1e3d26cf?follow=cdroms,sessions,disk_attachments.disk,graphics_consoles,nics,snapshots"
helpers.js:20 _httpGet: url="/api/vms/e5b0c745-ae54-424d-bf61-598a1e3d26cf?follow=cdroms,sessions,disk_attachments.disk,graphics_consoles,nics,snapshots", headers="{"Authorization":"Bearer <snip>","Accept-Language":null,"Filter":false,"Accept":"application/json"}"
index.js:257 Uncaught TypeError: _intl.msg[(sequence[key] + "DeviceTooltip")] is not a function
    at index.js:257
    at immutable.js:3016
    at List.__iterate (immutable.js:2206)
    at IndexedIterable.mappedSequence.__iterateUncached (immutable.js:3015)
    at seqIterate (immutable.js:604)
    at IndexedIterable.IndexedSeq.__iterate (immutable.js:320)
    at IndexedIterable.toArray (immutable.js:4258)
    at List [as constructor] (immutable.js:2065)
    at reify (immutable.js:3570)
    at List.map (immutable.js:4401)
(anonymous) @ index.js:257
(anonymous) @ immutable.js:3016
List.__iterate @ immutable.js:2206
mappedSequence.__iterateUncached @ immutable.js:3015
seqIterate @ immutable.js:604
IndexedSeq.__iterate @ immutable.js:320
toArray @ immutable.js:4258
List @ immutable.js:2065
reify @ immutable.js:3570
map @ immutable.js:4401
render @ index.js:254
finishClassComponent @ react-dom.development.js:13085
updateClassComponent @ react-dom.development.js:13047
beginWork @ react-dom.development.js:13715
performUnitOfWork @ react-dom.development.js:15741
workLoop @ react-dom.development.js:15780
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
replayUnitOfWork @ react-dom.development.js:15194
renderRoot @ react-dom.development.js:15840
performWorkOnRoot @ react-dom.development.js:16437
performWork @ react-dom.development.js:16358
performSyncWork @ react-dom.development.js:16330
interactiveUpdates$1 @ react-dom.development.js:16597
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4528
react-dom.development.js:14113 The above error occurred in the <VmDetail> component:
    in VmDetail (created by Connect(VmDetail))
    in Connect(VmDetail) (created by VmDetailPage)
    in VmDetailPage (created by Connect(VmDetailPage))
    in Connect(VmDetailPage) (created by PageRouter)
    in div (created by PageRouter)
    in div (created by PageRouter)
    in PageRouter (created by Connect(PageRouter))
    in Connect(PageRouter) (created by Route)
    in Route (created by withRouter(Connect(PageRouter)))
    in withRouter(Connect(PageRouter)) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter) (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in IntlProvider
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:14113
logError @ react-dom.development.js:14152
update.callback @ react-dom.development.js:14809
callCallback @ react-dom.development.js:10764
commitUpdateQueue @ react-dom.development.js:10808
commitLifeCycles @ react-dom.development.js:14283
commitAllLifeCycles @ react-dom.development.js:15342
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:15481
completeRoot @ react-dom.development.js:16496
performWorkOnRoot @ react-dom.development.js:16440
performWork @ react-dom.development.js:16358
performSyncWork @ react-dom.development.js:16330
interactiveUpdates$1 @ react-dom.development.js:16597
interactiveUpdates @ react-dom.development.js:2150
dispatchInteractiveEvent @ react-dom.development.js:4528
index.js:257 Uncaught TypeError: _intl.msg[(sequence[key] + "DeviceTooltip")] is not a function
    at index.js:257
    at immutable.js:3016
    at List.__iterate (immutable.js:2206)
    at IndexedIterable.mappedSequence.__iterateUncached (immutable.js:3015)
    at seqIterate (immutable.js:604)
    at IndexedIterable.IndexedSeq.__iterate (immutable.js:320)
    at IndexedIterable.toArray (immutable.js:4258)
    at List [as constructor] (immutable.js:2065)
    at reify (immutable.js:3570)
    at List.map (immutable.js:4401)
```

**Comment by sjd78** [comment] 2018-11-19 02:48
Same root cause as issue #788 - the `VmDetail` page would fail when the VM had >2 boot devices.  While the VM may contain >2 boot devices, the page would run out of device labels and fail to load a label for the 3rd device.

The problem was fixed in #801 by limiting the page to displaying the first 2 boot devices in the VM.

**Closed** 2018-11-19 04:00 UTC
Labels: bug, severity_low
