### ISSUE TITLE
while deleting a snapshot, 'Create Snapshot' button, restore and delete buttons of other snapshots not disabled

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#808] opened 2018-10-08 08:39 UTC
When one snapshot is being deleted, 'Create Snapshot' button, restore and delete buttons of other snapshots are not disabled.
![selection_028](https://user-images.githubusercontent.com/16017126/46599010-5c063680-cae6-11e8-8286-092e94848267.png)

**Comment by bond95** [comment] 2018-10-08 11:11
Duplicate of https://github.com/oVirt/ovirt-web-ui/issues/792 and fixed in https://github.com/oVirt/ovirt-web-ui/pull/798

**Closed by bond95** 2018-10-08 11:11 UTC
