### ISSUE TITLE
failed to power off

### ISSUE THREAD

**Issue by finleyredant** [oVirt/ovirt-web-ui#1190] opened 2020-04-18 13:59 UTC
Description of problem:
![image](https://user-images.githubusercontent.com/28280249/79639627-3eab3180-818d-11ea-8d3b-91aa64abf33c.png)
I can't get logged in again. It looks like it still thinks it needs to power down, but at the same time believes it is powered down.  

VM Portal version number:1.6.0-1

oVirt version number: 4.3

Browser and version: edge

Steps to Reproduce:
1.
2.
3.

Actual results: Can't log in

Expected results: Can log in

Additional info: It worked before

**Comment by sjd78** [comment] 2020-05-04 16:41
@finleyredant - What specifically do you mean by "can't get logged in"?  You can't get logged in to VM Portal after this happend?  Can't open the console of the "Powering down" VM?

The error sounds like a problem with the VM or the ovirt-engine itself.

Did you try a force shutdown of the VM?

Did the VM powerdown after some time by itself?

**Comment by sgratch** [comment] 2020-08-06 10:21
@finleyredant ping?

**Comment by sgratch** [comment] 2021-06-09 11:21
Since there is no reply from issue reporter for more than a year and the issue for reproducing is not  clear then I'm closing this.
Please reopen if it still reproduced and you can supply more details as mentioned here https://github.com/oVirt/ovirt-web-ui/issues/1190#issuecomment-623574495

**Closed by sgratch** 2021-06-09 11:21 UTC
