### ISSUE TITLE
Cannot create new VM - the wizard is stuck on the first step (Basic Settings)

### ISSUE THREAD

**Issue by pnovotny** [oVirt/ovirt-web-ui#1379] opened 2021-03-12 14:03 UTC
Description of problem:
The VM wizard does not allow user to go from the first step (Basic Settings) to the next one. The 'Next' button is disabled, although all the required fields were set.
This practically prevents any user to create any VM.

VM Portal version number:
ovirt-web-ui-1.6.7-1.el8ev.noarch

oVirt version number:
ovirt-engine-4.4.5.9-0.1.el8ev.noarch

Browser and version:
Firefox 86, Chromium 89

Steps to Reproduce:
1. Open 'Create Virtual Machine' wizard dialog.
2. Fill in all the mandatory fields (Name, Cluster, Provision Source=Template, Template, OS, Memory, CPUs and Optimized For). The values don't really matter.
3. Try to go to the next step - Networking.

Actual results:
The VM wizard doesn't let you go to the next step.

Expected results:
Allow user to go to the next step.

Additional info:
No errors or warnings were logged to the browser console.

Screen:
![create-vm-stuck-on-the-first-step](https://user-images.githubusercontent.com/314377/110949773-4b0b2080-8343-11eb-815a-676a87e3694f.png)

**Comment by isaranova** [comment] 2021-03-12 14:18
The issue was also reproduced on this version of ovirt-engine:
ovirt-engine-4.4.5.8-0.9.el8ev.noarch

The issue is not reproducible on this version of webui and ovirt-engine:
ovirt-engine-4.4.5.8-0.0.master.20210224204932.gita37fb2d985c.el8.noarch
ovirt-web-ui-1.6.8-0.20210215.gita151047.el8.noarch

**Comment by sjd78** [comment] 2021-03-12 14:43
Patch #1376 released with ovirt-web-ui-1.6.8 should fix this problem.

**Comment by rszwajko** [comment] 2021-03-15 08:39
@pnovotny 
It seems that this is bug on the oVirt's backend.  The new format(see below) is just default [AbstractMap.toString()](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/AbstractMap.html#toString()). Most likely a map instance is getting serialized to string by accident. This violates the basic REST API principles by introducing a new serialization format.
Additionally all REST API changes should be backward compatible and this is clearly not the case here.

@sgratch @sjd78 
IMHO  a temporary workaround in Web UI should be implemented only if backend won't be able to fix this in time.

New format:
```
{
  "values" : {
    "system_option_value" : [ {
      "value" : "{ppc=384, x86=384, s390x=384}",
      "version" : "4.2"
    }, {
      "value" : "{ppc=384, x86=384, s390x=384}",
      "version" : "4.3"
    }, {
      "value" : "{ppc=384, x86=384, s390x=384}",
      "version" : "4.4"
    }, {
      "value" : "{ppc=384, x86=512, s390x=384}",
      "version" : "4.5"
    }, {
      "value" : "{ppc=384, x86=512, s390x=384}",
      "version" : "4.6"
    } ]
  },
  "name" : "MaxNumOfVmCpus",
  "href" : "/ovirt-engine/api/options/MaxNumOfVmCpus",
  "id" : "MaxNumOfVmCpus"
}
```

**Comment by oliel** [comment] 2021-03-15 09:29
When it comes to configuration items, the API displays their values as they are saved in the database. 

We could create an architecture for supporting version-specific configuration items, but there was no request for such support and I personally don't think it's worth the effort

The existing implementation does not violate any REST principle AFAIK.

**Comment by ahadas** [comment] 2021-03-15 09:58
> When it comes to configuration items, the API displays their values as they are saved in the database.
> 
> We could create an architecture for supporting version-specific configuration items, but there was no request for such support and I personally don't think it's worth the effort

+1
Generally, clients shouldn't rely on the internal representation of the configuration values in oVirt - as we may drop ones that are no longer used (like those for feature supported) or change their format.
The VM portal is an exception - it tries to provide the same user experience the webadmin does so it needs to know things like this limit but the fact that it relies on a query that returns the internal representation of config values is a flaw in its design.

**Comment by sjd78** [comment] 2021-03-15 18:13
> Additionally all REST API changes should be backward compatible and this is clearly not the case here.

Not a REST change - it's a data change.

> 
> @sgratch @sjd78
> IMHO a temporary workaround in Web UI should be implemented only if backend won't be able to fix this in time.
> 
> New format:
> 
> ```
> {
>   "values" : {
>     "system_option_value" : [ {
>       "value" : "{ppc=384, x86=384, s390x=384}",
>       "version" : "4.2"
>     }, {
>       "value" : "{ppc=384, x86=384, s390x=384}",
>       "version" : "4.3"
>     }, {
>       "value" : "{ppc=384, x86=384, s390x=384}",
>       "version" : "4.4"
>     }, {
>       "value" : "{ppc=384, x86=512, s390x=384}",
>       "version" : "4.5"
>     }, {
>       "value" : "{ppc=384, x86=512, s390x=384}",
>       "version" : "4.6"
>     } ]
>   },
>   "name" : "MaxNumOfVmCpus",
>   "href" : "/ovirt-engine/api/options/MaxNumOfVmCpus",
>   "id" : "MaxNumOfVmCpus"
> }
> ```

Old format:
```js
{
  "values" : {
    "system_option_value" : [ {
      "value" : "384",
      "version" : "4.2"
    }, {
      "value" : "384",
      "version" : "4.3"
    }, {
      "value" : "384",
      "version" : "4.4"
    }, {
      "value" : "384",
      "version" : "4.5"
    } ]
  },
  "name" : "MaxNumOfVmCpus",
  "href" : "/ovirt-engine/api/options/MaxNumOfVmCpus",
  "id" : "MaxNumOfVmCpus"
}
```

And as long as the value format is consistent across versions, the data transforms can be done the same way.

**Comment by sjd78** [comment] 2021-04-17 00:27
Note: PR #1376 patches this issue enough for create VM to function.  Issue #1380 is a followup to the specific data change underlying the cause of this issue.  Future changes will be made against #1380.

**Closed** 2021-04-17 00:28 UTC
Labels: Severity: High
