### ISSUE TITLE
Refreshing the VM grid shows all the VMs as if the user was an administrator

### ISSUE THREAD

**Issue by isaranova** [oVirt/ovirt-web-ui#1330] opened 2020-11-11 02:01 UTC
Description of problem:
When entering the VM Portal, the VM grid contains only the VMs that user is supposed to see (permissions) and VM pools only are shown if the user did not allocate any VMs yet. However, after pushing the refresh button all the VMs including possible VM Pool VMs appear as if the user was an admin.

VM Portal version number:
ovirt-web-ui-1.6.6-0.20201030.gitf464801.el8.noarch

oVirt version number:
ovirt-engine-4.4.4-0.0.master.20201109161351.git5dac13e7e22.el8.noarch
ovirt-engine-4.4.3.10-0.1.el8ev.noarch

Browser and version:
firefox-82.0.2-1.fc31.x86_64

Steps to Reproduce:
1. Login as UserRole user
2. Click on refresh button
3. Check that you can still see only the VMs you have permissions for

Actual results:
User sees all the VMs and VM Pool VMs.

Expected results:
User sees only the VMs he has permissions for

**Comment by isaranova** [comment] 2020-11-20 14:25
After investigating the issue a bit more, I got some more reproduction steps:
- The issue seems to be involving only VM Pools.
- The issue seems to be present only if the user has global UserRole, directly applied UserRole to a specific VM or VM Pool does not reproduce the issue.
- Refresh done by the VM Portal itself does not always reproduce the issue.
- Hard refresh (F5) does "fix" the issue.
- VM Portal refresh does reproduce the issue always even after hard refresh.
- User can see all the VM Pool VMs and run all of them exceeding the limit of VM Pool VMs per user.
- The VM Pool card behaves correctly and after running more VM Pool VMs than the user is limited to, the VM Pool card disappears but all of the VM Pool VMs are still present and able to be run.

**Comment by sjd78** [comment] 2020-11-24 16:59
@isaranova , @sgratch - If a user has a global `UserRole`, why wouldn't they see all VMs in the system?  Wouldn't the role inherit to everything?

**Comment by hstastna** [comment] 2020-11-24 17:40
**Steps to reproduce:**
1. As an admin, create some VM pool in Admin portal ("The issue seems to be involving only VM Pools.")
2. Log in as a user with the _UserRole_ permission to VM Portal
=> you can see the VM Pool (step 1) (with the proper number of "Available VMs from this pool" for the user according to the limit, in the pool card), but not the VM Pool VMs by themselves
3. Click on the _Refresh_ button up right in the VM Portal
=> all the VM Pool VMs do appear + it is possible to run them and to exceed the limit of the available VM Pool VMs per user

**Actual result:**
![actual](https://user-images.githubusercontent.com/13417815/100131065-d55a7200-2e83-11eb-95ea-1ff75ced262c.png)

**Expected result:**
![expect](https://user-images.githubusercontent.com/13417815/100131086-de4b4380-2e83-11eb-9f20-35162e650f3d.png)

**Comment by sgratch** [comment] 2020-11-25 19:41
> @isaranova , @sgratch - If a user has a global `UserRole`, why wouldn't they see all VMs in the system? Wouldn't the role inherit to everything?

@sjd78 the user should see all VMs in the system and even all pools in the system if he has a global `UserRole` but he shouldn't see the pool vms that were not assigned to him. The `UserRole` is not inherited automatically to all pool vms but only to those that were assigned to the user.

**Closed** 2020-12-06 14:24 UTC

**Comment by isaranova** [comment] 2021-01-21 18:13
LGTM
