### ISSUE TITLE
OS icons cached in local storage are not updated if the icon changes on the server

### ISSUE THREAD

**Issue by sjd78** [oVirt/ovirt-web-ui#739] opened 2018-08-23 15:08 UTC
Even after the "Other OS" icon was updated on the ovirt-engine (see https://gerrit.ovirt.org/#/c/93007/), web-ui keeps using its cached copy of the image.  The icons need to be purged from the browser "Local Storage" to force the new icon to be reloaded.

web-ui makes an assumption that the `data-url` of any given icon id will not change.  Once it is loaded in Local Storage it stays there.

There are 2 things that can be done:
 1. On the ovirt-engine, when an icon is updated, change it's id
 2. On the web-ui, add cache invalidation to the icons stored in browser local storage

**Comment by sjd78** [comment] 2018-08-23 19:46
Related to but different from #606

**Comment by sgratch** [comment] 2021-06-09 11:15
Since no user complained and the issue is opened for more than 2 years then closing it.
Please re-open if you think it's still important to handle.

**Closed by sgratch** 2021-06-09 11:15 UTC
Labels: Severity: Low, Type: Bug
