### ISSUE TITLE
When editing disks/vNICs, no use for save button only close

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#978] opened 2019-02-27 08:28 UTC
Feature enhancement request:
When editing disks/vNICs the edit action are done separately. So close and save buttons do the same. Only one can stay, not sure which one could make more sense. Maybe close.

**Comment by sgratch** [comment] 2019-08-07 12:09
@leistnerova This seems not relevant anymore. Can you please approve that?

**Comment by bond95** [comment] 2019-08-29 12:18
@sgratch it is still relevant. We still have two button at bottom of cards and they still doing the same function.
![image](https://user-images.githubusercontent.com/3332176/63939538-ce1d9c00-ca67-11e9-8006-df0053684d57.png)

@lwrigh any thoughts about that?

**Comment by lwrigh** [comment] 2019-08-29 13:49
@bond95 @sgratch I would tend to agree with Sharon that it's not relevant anymore.

**Comment by leistnerova** [comment] 2019-08-29 14:06
@lwrigh @sgratch Why it is not relevant? I agree with Bohdan. It is still confusing what does the check button do, when editing was already done with other buttons/dialogs.

**Comment by lwrigh** [comment] 2019-08-29 14:20
When we did baseline usability testing of VM portal users didn't have too much trouble with making edits to the different fields that feature the close and save buttons

**Comment by bond95** [comment] 2019-09-03 11:47
> When we did baseline usability testing of VM portal users didn't have too much trouble with making edits to the different fields that feature the close and save buttons

@lwrigh @sgratch but what is purpose of two buttons if they do same thing? Maybe better remove one of them, or to do similar as we have in snapshot card?
![image](https://user-images.githubusercontent.com/3332176/64170797-524d9600-ce51-11e9-8e92-6fc2567c6e08.png)

**Comment by lwrigh** [comment] 2019-09-03 15:15
The first pencil button puts the card into an edit mode where the user can edit any of disks or NICs, then the second pencil button is to edit an individual disk or NIC.

**Comment by leistnerova** [comment] 2019-09-04 05:19
Now I'm not sure we understand each other... my fault. I'm talking about these two buttons.

![nics](https://user-images.githubusercontent.com/29575480/64227560-36470480-cee4-11e9-9631-54598170c0a8.png)

**Comment by sgratch** [comment] 2019-12-08 23:34
@lwrigh  what is the difference between those 2 buttons? The close and save buttons do the exact  same thing. 

 > ![nics](https://user-images.githubusercontent.com/29575480/64227560-36470480-cee4-11e9-9631-54598170c0a8.png)

**Comment by lwrigh** [comment] 2019-12-09 12:33
They are mainly for activating/deactivating making edits to the NICs card.

**Comment by sgratch** [comment] 2019-12-09 12:58
> They are mainly for activating/deactivating making edits to the NICs card. They kind of act like higher level save and cancel buttons. They also help to save some space since they do not spell out the words 'Save' and 'Cancel'.

The problem is that **both** buttons behave like "Save", i.e. when you made changes to NICs/Disks and you click either one of those buttons, the changes are saved. So we need to either change the behaviour of the "X" button or get rid of one of them.

**Comment by leistnerova** [comment] 2019-12-09 13:09
I'll try to be more specific here. From what I understand in this case both button are more like 'Close'. And that is the main thing that is confusing, because edit and create NIC is already saved by modal dialogs that appear and user doesn't have to click something else to save the changes.
So no other 'Save' action is needed here, the buttons just allow to show/hide edit/create/delete buttons.

**Comment by sgratch** [comment] 2019-12-09 13:23
Why keeping that redundancy? Users may be confused by thinking that the "X" button will cancel their changes...like on other cards like VM details.

**Comment by leistnerova** [comment] 2019-12-09 13:28
> Why keeping that redundancy? Users may be confused by thinking that the "X" button will cancel their changes...like on other cards like VM details.

@sgratch I'm not finally decided, this angle of view is alright too.

**Comment by sgratch** [comment] 2019-12-10 12:31
I'm not sure but let's wait to see if it's not confusing customers, so l will close this issue for now. 
Please re-open in case you think it should be handled.

**Closed by sgratch** 2019-12-10 12:31 UTC
Labels: Flag: Needs QE, Flag: Needs UI review, Priority: Low, Scope: 2, Type: Enhancement
