### ISSUE TITLE
when creating a snaphsot, restore and delete icons of other snapthots are not disabled

### ISSUE THREAD

**Issue by samuelmacko** [oVirt/ovirt-web-ui#810] opened 2018-10-08 08:51 UTC
similar to #808 
when a snapshot is being created, only that snapshot has delete and restore buttons disabled, others don't. 
![selection_029](https://user-images.githubusercontent.com/16017126/46599596-0a5eab80-cae8-11e8-8c14-afcb4e6db194.png)

**Comment by bond95** [comment] 2018-10-08 11:11
Duplicate of https://github.com/oVirt/ovirt-web-ui/pull/798 and fixed in https://github.com/oVirt/ovirt-web-ui/pull/798

**Closed by bond95** 2018-10-08 11:11 UTC
