### ISSUE TITLE
CreateVmWizard: Blank OS in Basic settings after choosing some clusters

### ISSUE THREAD

**Issue by hstastna** [oVirt/ovirt-web-ui#1307] opened 2020-10-13 19:49 UTC
There's an issue in the _Basic settings_ step of the wizard: after choosing a _Cluster_, blank/none of the OS is chosen for the _Operating system_ field/drop down. This does not happen always, only with some of the clusters available in the appropriate drop down.

I've found that this issue is related to the **CPU type** chosen in webadmin when creating a cluster. Looks like choosing/selecting the proper OS in the drop down works fine in the Basic settings only when selecting clusters created with any _CPU Type_ available for _CPU architecture_ _x86_64_.

**Steps to Reproduce:**
1. In webadmin, create a cluster in one of the two ways:
A) _CPU Architecture_ `undefined` and _CPU Type_ `Auto Detect`:
![webadmin](https://user-images.githubusercontent.com/13417815/95909377-accc5c00-0d9e-11eb-8237-223d0a7f33a9.png)
B) `ppc64` and any of the two available CPU types:
![c2](https://user-images.githubusercontent.com/13417815/95901545-cf0cac80-0d93-11eb-9b24-1a534650f950.png)
2. In web UI, open the Create VM Wizard, select the created cluster in the drop down, in _Basic settings_ step
=> look at the _Operating System_ drop down

---

**Actual results:** 
Nothing is selected as the _Operating System_:
![n1](https://user-images.githubusercontent.com/13417815/95902957-cf0dac00-0d95-11eb-8320-29582d80d4db.png)
A) the drop down is empty!
![a](https://user-images.githubusercontent.com/13417815/95909185-5a8b3b00-0d9e-11eb-805a-c949a61e058b.png)

B) at least, the drop down is not empty and contains the proper items
![b](https://user-images.githubusercontent.com/13417815/95909190-5ced9500-0d9e-11eb-9f7d-d1b7cd076448.png)

In addition, after adding a _Name_ for a VM and choosing a _CD_ (or _Blank_ template), we are able to click on the Next button, even when no OS is selected, which is required field!
![power](https://user-images.githubusercontent.com/13417815/95904482-df268b00-0d97-11eb-957b-1f488057a6ca.png)
Then the _Other OS_ is displayed in the Review step, which is inconsistent with what we've seen in the Basic settings step:
![power2](https://user-images.githubusercontent.com/13417815/95904820-52c89800-0d98-11eb-978d-7444aa092aaa.png)

---

**Expected results:**
A) ???
B) probably the `Other OS` should be selected

---

**Additional info:**
If you won't be able to always reach the _Review_ step, it's because there's another and unrelated bug (it will be treated by anothert github issue):
`TypeError: basic.timeZone is undefined`
To avoid this, you need to play in the Basic settings a little bit, to choose some other options and then back to those you need.

**Comment by hstastna** [comment] 2020-10-14 11:18
**Related comment:** https://github.com/oVirt/ovirt-web-ui/pull/1288#discussion_r504596718

**Comment by sgratch** [comment] 2020-10-21 15:02
@hstastna a, b mentioned on your good and detailed description above represent the two reasons for this bug:

**a**- is a side effect of #1313. When the user choose a cluster with no host assigned (i.e. cpu architecture on webadmin is still undefined since it is set by the 1st assigned host) then there is no OS to choose and this use case is invalid at first place. 
Once #1313 will be fixed then this issue will be prevented.

**b** - when you choose a cluster compatible for a power pc cpu architecture then the list of supported OS is limited to a subset of the non ppc cpus. In that case we still need to auto choose the "other os" as  a default and I guess it was broken on basic settings dialog due to this change in list content.
So AFAIK choosing the "Other os" as default in case of ppc is the only thing that should be actually fixed here.

**Comment by hstastna** [comment] 2020-10-21 15:24
@sgratch I think you are right.

Regarding **b** - I was debugging it a little bit and the problem is that it is not possible to find the `0` id between that list of limited supported operating systems, obviously. They have different ids.. The "other OS" there has a different id than our usual "other OS" with the id `0`. And yes, I also think that in this situation, we just need to choose the other "other OS". This could be fixed quite easily, I think.

**Comment by bamsalem** [comment] 2020-12-14 13:48
I investigated this issue and I found the cause,
like @sgratch already mentioned, the options for ppc64 are limited, I found that the "Other OS" id is different between this architecture and other architectures:

But our default value for Other OS is compatible to other architecture.
I'll post PR that solves this issue soon.

@hstansa thanks for the detailed explanation, it was helpful :)

**Closed** 2021-01-28 10:27 UTC
