### ISSUE TITLE
autologout never triggers

### ISSUE THREAD

**Issue by michalskrivanek** [oVirt/ovirt-web-ui#399] opened 2017-11-10 12:56 UTC
followup to #308 
now since #388  there's no auto logout since the periodic refresh always revive the session. We need to distinguish periodic background polling from user actions and log out when there is no user activity

**Comment by gregsheremeta** [comment] 2019-02-13 23:29
duplicate of #955, closing since that one has more details

**Closed by gregsheremeta** 2019-02-13 23:29 UTC
Labels: Flag: Doesn't need UI review, Flag: Needs QE, Priority: Medium, Scope: 3, Severity: Medium, Type: Bug
