### ISSUE TITLE
Autologout after timeout

### ISSUE THREAD

**Issue by mareklibra** [oVirt/ovirt-web-ui#436] opened 2017-11-22 09:01 UTC
On web-ui side, implement automatic logout after user's inactivity for 30 minutes.

Within #308 , newly added `ovirt-api-scope` is used to avoid unexpected logout. As a side effect, the session never expires when data are repeatedly retrieved for e.g. read-only purpose.

Due to limitations on oVirt side, the easiest solution for automatic logout is to combine
- use of `ovirt-api-scope`
- with timeout monitored on client side.

When threshold is reached, web-ui actively invokes oVirt `logout` action.

---
Followup for: https://github.com/oVirt/ovirt-web-ui/issues/308

**Comment by jniederm** [comment] 2017-11-27 13:22
We need to make sure, that web-ui logout timeout will be <= the engine one since it is configurable (option `UserSessionTimeOutInterval`).

**Comment by gregsheremeta** [comment] 2018-07-31 00:56
duplicate of #399

**Closed by gregsheremeta** 2018-07-31 00:56 UTC
Labels: enhancement
