### ISSUE TITLE
Create VM / Storage - deleting value of disk Size input & changing focus causes crash

### ISSUE THREAD

**Issue by pnovotny** [oVirt/ovirt-web-ui#1285] opened 2020-09-02 15:58 UTC
Description of problem:
Deleting value of the disk Size input and changing focus away cases VM Portal to crash.
Console error: `TypeError: value must be a number or an array` (full trace in screenshot).

Screenshot:
![vmportal-disk-size-crash](https://user-images.githubusercontent.com/314377/92006258-c791c680-ed44-11ea-8697-ce64e00c65c8.png)

VM Portal version number:
ovirt-web-ui-1.6.4-1.el8ev.noarch

oVirt version number:
ovirt-engine-4.4.2.3-0.6.el8ev.noarch

Browser and version:
Firefox 80.0, Chromium 85.0

Steps to Reproduce:
1. Open Create VM wizard, fill mandatory values and go to Storage step.
2. Click Create disk button. 
3. In the new row, select & delete the Size value.
4. Change focus from the input (Tab away or click on different element).

Actual results:
VM Portal crash.

Expected results:
No crash. 

Additional info:

**Comment by bamsalem** [comment] 2020-09-16 12:38
@sgratch @pnovotny 
The issue solved since #1221 merged.
#1261 makes the field behave like create disk for existing VM dialog, in this dialog user can't delete size value, now this behavior applied for create vm wizard too.
This issue is already resolved.

**Comment by sgratch** [comment] 2020-09-16 16:11
Since it's already fixed as mentioned on https://github.com/oVirt/ovirt-web-ui/issues/1285#issuecomment-693377333, then the issue is closed as Not Reproduced.

**Closed by sgratch** 2020-09-16 16:11 UTC

**Comment by pnovotny** [comment] 2020-09-17 11:29
Verified in ovirt-web-ui-1.6.5-0.20200914.gitfd5cd81.el8
The disk size value cannot be deleted (and must be >=int(1)).
