### ISSUE TITLE
VM User Portal auto-logout(timeout) when UserSessionTimeOutInterval=-1

### ISSUE THREAD

**Issue by csreynolds** [oVirt/ovirt-web-ui#1109] opened 2019-08-30 14:31 UTC
Description of problem: User informed me today they could not log into the VM Portal. After investigation it looks like the UI is requesting a logout when  TimeOutInterval is -1. The admin portal works as expected and never logs out.
```
[root@cloud ~]# engine-config --get UserSessionTimeOutInterval
UserSessionTimeOutInterval: -1 version: general

```
```
/var/log/ovirt-engine/engine.log
2019-08-30 09:46:03,512-04 INFO  [org.ovirt.engine.core.sso.utils.AuthenticationUtils] (default task-4) [] User creynolds@COMPANY-LDAP successfully logged in with scopes: ovirt-app-admin ovirt-app-api ovirt-app-portal ovirt-ext=auth:sequence-priority=~ ovirt-ext=revoke:revoke-all ovirt-ext=token-info:authz-search ovirt-ext=token-info:public-authz-search ovirt-ext=token-info:validate ovirt-ext=token:password-access
2019-08-30 09:46:03,726-04 INFO  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (default task-4) [214c7367] EVENT_ID: USER_VDC_LOGIN(30), User creynolds@company-ldap-authz connecting from '1.2.3.4' using session 'biGolLongSessionIDkeY==' logged in.
2019-08-30 09:46:07,438-04 INFO  [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (default task-5) [6d8a13a3] EVENT_ID: USER_VDC_LOGOUT(31), User creynolds@company-ldap-authz connected from '1.2.3.4' using session 'biGolLongSessionIDkeY==' logged out.
2019-08-30 09:46:07,486-04 INFO  [org.ovirt.engine.core.sso.servlets.OAuthRevokeServlet] (default task-4) [] User creynolds@COMPANY-LDAP successfully logged out
```

As a workaround, I set UserSessionTimeOutInterval to 999 and the user can now log in.

VM Portal version number:
Red Hat Virtualization VM Portal Version 1.5.3-1

oVirt version number:
ovirt-engine-4.3.5.5-0.1.el7.noarch

Browser and version:
Same result on several browsers.

Steps to Reproduce:
1. engine-config --set UserSessionTimeOutInterval=-1
2. Try to log into User VM Portal.
3. Get logged out right away.

Actual results: User is logged out immediately.

Expected results: User is never automatically logged out.

**Comment by bond95** [comment] 2019-08-30 14:51
Duplicate of https://github.com/oVirt/ovirt-web-ui/issues/1085 and will be fixed in https://github.com/oVirt/ovirt-web-ui/pull/1087

**Closed by bond95** 2019-08-30 14:51 UTC
