### ISSUE TITLE
opening suspended VM's console returns Internal server error

### ISSUE THREAD

**Issue by leistnerova** [oVirt/ovirt-web-ui#516] opened 2018-03-06 08:37 UTC
When suspending VM, it stays in Up state for a while and in that time opening console returns error

Failed to retrieve VM console details
Internal Server Error

It should return some better readable error.

**Comment by jelkosz** [comment] 2018-03-06 08:38
@leistnerova can you please provide engine logs? I suspect some exception there...

**Comment by leistnerova** [comment] 2018-03-06 09:17
[logs.tar.gz](https://github.com/oVirt/ovirt-web-ui/files/1784241/logs.tar.gz)

**Comment by jelkosz** [comment] 2018-03-06 09:38
hmm, no exception, just a validation error:

```
2018-03-06 09:53:59,995+01 WARN  [org.ovirt.engine.core.bll.SetVmTicketCommand] (default task-2) [167ec13d] Validation of action 'SetVmTicket' failed for user admin@internal-authz. Reasons: VAR__ACTION__SET,VAR__TYPE__VM_TICKET,ACTION_TYPE_FAILED_VM_STATUS_ILLEGAL,VAR__VM_STATUS__SAVING_STATE
2018-03-06 09:53:59,997+01 ERROR [org.ovirt.engine.api.restapi.resource.BackendVmGraphicsConsoleResource] (default task-2) [] Operation Failed: SETTING_VM_TICKET_FAILED
```

which than shows up on frontend as:

`Reducing action:  {"type":"FAILED_EXTERNAL_ACTION","payload":{"message":"Failed to retrieve VM console details\nInternal Server Error","shortMessage":"Failed to retrieve VM console details","type":500,"action":{"type":"INTERNAL_CONSOLE","payload":{"vmId":"8a305dfc-579e-4bcb-a444-6040c0403950","consoleId":"7370696365"}}}}`

which is strange. It looks like a bug on API which does not return the error properly. Will target 1.4.0 so we can look into it better and probably move it to engine.

**Comment by bond95** [comment] 2018-06-14 12:37
Created bug on bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1591271

**Comment by gregsheremeta** [comment] 2018-07-31 14:13
@leistnerova API fix was merged today. Please re-test with tonight's engine snapshot.

**Comment by leistnerova** [comment] 2018-08-06 08:07
Now it returns:
Failed to retrieve VM console details
Conflict

@gregsheremeta  Is that intended error message?

tested on ovirt-engine-4.3.0-0.0.master.20180802141038.gitd9dc74f.el7.noarch
ovirt-web-ui-1.3.6-1.el7.centos.noarch

**Comment by gregsheremeta** [comment] 2018-08-07 00:05
Thanks. It should present a nice message to the user, something along the lines of "you cannot access the console while a snapshot operation is in progress."

**Comment by michalskrivanek** [comment] 2018-08-07 07:18
"...a machine is being suspended..."
Be very cautious about button disabling, we had a bad experience with that in webadmin since you generally do not have an up to date state information in frontend. I wouldn't want to go to webdamin complexity in ovirt-web-ui. Just rephrasing the message is good enough (note the state can also already be "Down" by the time the setvmticket arrives to backend)

**Comment by sgratch** [comment] 2019-07-31 15:05
Closing since this issue is not reproduced anymore after redesign

**Closed by sgratch** 2019-07-31 15:05 UTC
Labels: Flag: Needs QE, Flag: Needs UI review, Priority: Low, Severity: Low, Type: Bug
